### ISSUE TITLE
Broken interpolation of TARGET_BOARD_REAL in config files

### ISSUE THREAD

**Issue by evnm** [SamsungARTIK/build-artik#1]
`release.sh` fails upon invoking `release_rootfs.sh` due to incorrect interpolation in the `ROOTFS_TAG` variable. The following sequence of events illustrates the bug:

1. [`config/artik5.cfg` sources `config/common.cfg`](https://github.com/SamsungARTIK/build-artik/blob/artik-exynos/config/artik5.cfg#L1)
2. [`config/common.cfg` defines `ROOTFS_TAG` in terms of `TARGET_BOARD_REAL`](https://github.com/SamsungARTIK/build-artik/blob/artik-exynos/config/common.cfg#L23), which is itself defined later in `config/artik5.cfg`, and is thus empty within `config/common.cfg`
3. In `release_rootfs.sh`, `ROOTFS_TAG` is equal to `release//artik_os_1.0.0`, because the `TARGET_BOARD_REAL` path seqment is missing
4. The wget of the release tarball fails

We were able to fix this issue by [sourcing `common.cfg` after the definition of `TARGET_BOARD_REAL` within `config/artik5.cfg`](https://gist.github.com/evnm/0963361765363029f47a4d32bacb89d4). Managing variable dependencies between config files is a brittle undertaking, but it did the job.

**Comment by cometzero** [comment]
This issue has been fixed with below commit. Thanks.
https://github.com/SamsungARTIK/build-artik/commit/b5dce2cf1132e96b2828d936b9d3c86661245c42
