### ISSUE TITLE
artik530s 1G (artik533s) - A533s-OS-18.05.00. Correct verified boot. System reports only 512MB DRAM. 

### ISSUE THREAD

**Issue by ezaluzec** [SamsungARTIK/build-artik#10]
#### [Description]

This issue is to have the verified boot firmware images **corrected** on the artik530s 1G (artik533s) platform to make 1GB DRAM available. Verified boot and secure boot is a pivotal security requirement when providing customers with hardware-based solutions using the artik530s 1G (artik533s). 

Based on the SamsungARTIK repository branch, `A533s-OS-18.05.00`, firmware images with verified boot for the artik530s 1G (artik533s) platform do not support 1GB memory on the system. Only 512MB memory is available and reported by the system. 
 
#### [Steps To Reproduce]

1. Fetch & initialize artik533s build from build-artik README guide

		mkdir artik533s; cd artik533s; repo init -u https://github.com/SamsungARTIK/manifest.git -m artik533s_bsp.xml; repo sync;

2. Modify the SamsungARTIK board support packages based on [Verified Boot](https://developer.artik.io/documentation/artik/advanced-concepts/verified-boot.html#verified-boot) documentation from `developer.artik.io`.

3. Modify u-boot-artik's `artik533_raptor_defconfig` with changes to support verified-boot

		+CONFIG_FIT_SIGNATURE=y
		+CONFIG_RSA=y
		+CONFIG_FIT_VERBOSE=y
		-CONFIG_OF_EMBED=y

4. Modify u-boot-artik's `s5p4418-artik530-raptor-common.dtsi` with changes to support verified-boot

		+	signature {
		+		key-mfgtest_dev {
		+			required = "conf";
		+			algo = "sha256,rsa2048";
		+			key-name-hint = "vboot_keys";
		+		};
		+	};

5. Modify u-boot-artik's `arch/arm/dts/Makefile` with changes to support verified-boot

		+DTC_FLAGS += -R 4 -p 0x1000

6. Modify build-artik's vboot scripts to correctly support verified-boot

		+	sed -i -e 's/bootcmd=run .*/bootcmd=run vboot/g' default_envs_vboot.txt
		+	cp default_envs_vboot.txt default_envs_vboot.txt.bak
		+	cat ${EXTRA_VBOOT_ENV_FILE} >> default_envs_vboot.txt
		+	tools/mkenvimage -s 16384 -o params_vboot.bin default_envs_vboot.txt

		+	dd if=${B}/uInitrd of=${B}/initrd.gz bs=1 skip=64
		+	mkdir -p ${B}/initrd
		+	cd ${B}/initrd
		+	zcat ${B}/initrd.gz | cpio -ivd
		+	cp ${B}/modules.img.verity ./
		+	find . | cpio -o -H newc | gzip > ${B}/initrd.gz

		+	${B}/tools/mkimage -f ${ITS_NAME} ${FIT_IMAGE}
		+	${B}/tools/mkimage -k ${KEY_DIR} -r -F -K ${B}/u-boot.dtb ${FIT_IMAGE}
		+	cat ${B}/u-boot.bin ${B}/u-boot.dtb > ${B}/u-boot-dtb.bin

		+	cp ${B}/params_vboot.bin ${B}/params_emmc.bin
		+	cp ${B}/params_sdvboot.bin ${B}/params_sd.bin
		
7. Modify u-boot-artik's default environment text file used by default environment binary file to support verified-boot (NOTE: These modifications were incomplete in all SamsungARTIK branches for vboot)

		+v_gen_iaddr=\
		+    setexpr v_itbaddr $sdram_base + $v_itb_offs
		+v_itb_offs=0x0f000000
		+v_itb_file=kernel_fdt.itb
		+v_boot_cmd_itb=\
		+    run v_load_itb\
		+    bootm $v_itbaddr
		+v_bootpart=2
		+v_set_rootpart=setexpr v_rootpart 5 + $v_bootpart
		+v_load_args=\
		+    run factory_load\
		+    run v_set_rootpart\
		+    setenv bootargs ${console} root=/dev/mmcblk${rootdev}p${v_rootpart} ${root_rw} rootfstype=${rootfs_type} ${recoverymode} ${ota} nr_cpus=${nr_cpus} ${loglevel} ${opts} bootfrom=${v_bootpart} rescue=${rescue} board_type=${board_type}
		+v_ramfsboot=\
		+    run v_gen_iaddr\
		+    run v_load_args\
		+    run v_boot_cmd_itb
		+vboot=run v_ramfsboot
		+v_load_itb=\
		+    ret=0\
		+    ext4load mmc ${rootdev}:${v_bootpart} ${v_itbaddr} ${v_itb_file} && setexpr ret 1\
		+    if test $ret -eq 0; then\
		+        if test $v_bootpart -eq 2; then\
		+            setenv v_bootpart 3\
		+        else\
		+            setenv v_bootpart 2\
		+        fi\
		+        setenv rescue 1\
		+        ext4load mmc ${rootdev}:${v_bootpart} ${v_itbaddr} ${v_itb_file}\
		+        run v_load_args\
		+    fi
		+v_sdload_itb=\
		+    ret=0\
		+    setenv v_bootpart 1\
		+    ext4load mmc ${rootdev}:${v_bootpart} ${v_itbaddr} ${v_itb_file} && setexpr ret 1
		+v_sdboot_cmd_itb=\
		+    run v_sdload_itb\
		+    bootm $v_itbaddr
		+v_sdset_rootpart=\
		+    setenv v_rootpart 3
		+v_sdload_args=\
		+    run factory_load\
		+    run v_sdset_rootpart\
		+    setenv bootargs ${console} root=/dev/mmcblk${rootdev}p${v_rootpart} ${root_rw} rootfstype=${rootfs_type} ${recoverymode} ${ota} nr_cpus=${nr_cpus} ${loglevel} ${opts} bootfrom=${v_bootpart} rescue=${rescue} board_type=${board_type}
		+v_sdramfsboot=\
		+    run v_gen_iaddr\
		+    run v_sdload_args\
		+    run v_sdboot_cmd_itb
		+recoveryvboot=\
		+    run gen_sdrecaddr\
		+    run recovery_cmd\
		+    run v_sdramfsboot

8. Modify linux-artik's `artik530_raptor_defconfig` with changes to support verified-boot

		+CONFIG_DM_VERITY=y
		
9. Run release script with verified boot options

		./release.sh -c config/artik533s_ubuntu.cfg -m --vboot --vboot-keydir $PWD/verified-boot/dev_key --vboot-its $PWD/verified-boot/kernel_fit_verify.its
		
10. Install artik533s_sdcard-UNRELEASED-`<date>`.img on microSD card and boot artik530s 1G (artik533s) platform from SD.

11. Login to system with default credentials `root/root` and run system command from terminal, `cat /proc/meminfo`

#### [Expected Result]

Verify memory total is 1GB

		[root@artik ~]# cat /proc/meminfo
		MemTotal:         990460 kB

#### [Actual Result]

		[root@artik ~]# cat /proc/meminfo
		MemTotal:         470732 kB

###### [Components]
| Component | Component Version |
| :---: | :---: |
| Verified boot | A533s-OS-18.05.00 |

###### [Applicable Hardware Platform]
| Platform Name | Platform Version | Processor Type |
| :--- | :---: | :---: |
| artik530s 1G (artik533s) | A533s-OS-18.05.00 | ARM |

##### [Related Information]

The following wiki aided in modifying the build-artik scripts which were incomplete or missing verified boot steps. [Verified Boot – Introduction to U-Boot’s Secure Boot](https://www.pacificsimplicity.ca/blog/verified-boot-%E2%80%93-introduction-u-boot%E2%80%99s-secure-boot)

**Comment by cometzero** [comment]
Hi,
You should change load / entry addresses of its file. Please see below example its file for artik530s 1G(artik533s).

/dts-v1/;

/ {
	description = "Linux kernel and FDT blob for ARTIK-533(530 1G)";
	#address-cells = <1>;

	images {
		kernel {
			description = "Linux kernel for ARTIK-533";
			data = /incbin/("./zImage");
			type = "kernel";
			arch = "arm";
			os = "linux";
			compression = "none";
			**load = <0x71080000>;
			entry = <0x71080000>;**
			hash {
				algo = "sha1";
			};
			signature {
				required = "image";
				algo = "sha1,rsa2048";
				key-name-hint = "dev";
			};
		};
		ramdisk {
			description = "ramdisk";
			data = /incbin/("./initrd.gz");
			type = "ramdisk";
			arch = "arm";
			os = "linux";
			compression = "gzip";
			**load = <0x7a000000>;**
			hash {
				algo = "sha1";
			};
			signature {
				required = "image";
				algo = "sha1,rsa2048";
				key-name-hint = "dev";
			};
		};
		fdt-rev00 {
			description = "FDT blob for artik533 rev00";
			data = /incbin/("./s5p4418-artik533-raptor-rev00.dtb");
			type = "flat_dt";
			arch = "arm";
			compression = "none";
			**load = <0x7b000000>;**
			hash {
				algo = "sha1";
			};
			signature {
				required = "image";
				algo = "sha1,rsa2048";
				key-name-hint = "dev";
			};
		};
	};
	configurations {
		default = "rev00";
		rev00 {
			description = "Boot Linux kernel with FDT blob";
			kernel = "kernel";
			ramdisk = "ramdisk";
			fdt = "fdt-rev00";
			signature {
				required = "image";
				algo = "sha1,rsa2048";
				key-name-hint = "dev";
				sign-images = "fdt", "kernel", "ramdisk";
			};
		};
	};
};

**Comment by ezaluzec** [comment]
@cometzero, thank you for the input. Changing the entry & load addresses in the its file allowed system to correctly report 1GB of total memory. Noticing the addresses of [CONFIG_SYS_TEXT_BASE](https://github.com/SamsungARTIK/u-boot-artik/blob/A533s-OS-18.05.00/include/configs/artik533_raptor.h#L25) for artik533s compared to artik530 was overlooked. 

        ~# cat /proc/meminfo
        MemTotal:         990264 kB

While working to identify the cause of this issue, I noticed that the [build-artik build_uboot.sh](https://github.com/SamsungARTIK/build-artik/blob/A533s-OS-18.05.00/build_uboot.sh#L130) script uses a default nsih artik530 [raptor-sd.txt](https://github.com/SamsungARTIK/u-boot-artik/blob/A533s-OS-18.05.00/tools/nexell/nsih/raptor-sd.txt) file when generating the bootloader.img. This default raptor-sd.txt file has parameters for artik530 and not artik530s (artik533s 1GB). There exists an [nsih-artik533s.txt](https://github.com/SamsungARTIK/boot-firmwares-artik533s/blob/A533s-OS-18.05.00/nsih-artik533s.txt) file. Do you know if there is any significance in updating build scripts to use nsih-artik533s.txt when generating the bootloader.img as opposed to using the raptor-sd.txt? 

This issue can be closed.
